[package]
name = "read_ram"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
windows = { version = "0.59", features = ["Win32_Foundation", "Win32_System_Threading", "Win32_System_Diagnostics_ToolHelp"] }